application: turklime-jjh
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /(task|submit)
  script: app.py

- url: /.*
  script: app.py
  login: required
